android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC
kotlin.daemon.jvmargs=-Xmx3g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
# Requerido con Kotlin integrado + KSP (ver mensaje AGP si se quita).
android.disallowKotlinSourceSets=false
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
