package com.example.optoapp.domain

import com.example.optoapp.data.EvaluacionClinica
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.time.Instant
import java.time.LocalDate

data class HistorialSyncResult(val uploaded: Int, val downloaded: Int)

@Serializable
data class EvaluacionRemota(
    val id: String,
    @SerialName("paciente_id") val pacienteId: String,
    val fecha: String,
    @SerialName("optica_id") val opticaId: String,
    @SerialName("motivo_consulta") val motivoConsulta: String = "",
    val sintomas: String = "",
    @SerialName("antecedentes_personales_oculares") val antecedentesPersonalesOculares: String = "",
    @SerialName("antecedentes_personales_sistemicos") val antecedentesPersonalesSistemicos: String = "",
    @SerialName("antecedentes_familiares_oculares") val antecedentesFamiliaresOculares: String = "",
    @SerialName("antecedentes_familiares_sistemicos") val antecedentesFamiliaresSistemicos: String = "",
    val medicacion: String = "",
    val alergias: String = "",
    @SerialName("necesidad_visual") val necesidadVisual: String = "",

    // AV
    @SerialName("av_sc_od_lejos") val avScOdLejos: String = "",
    @SerialName("av_sc_oi_lejos") val avScOiLejos: String = "",
    @SerialName("av_sc_od_cerca") val avScOdCerca: String = "",
    @SerialName("av_sc_oi_cerca") val avScOiCerca: String = "",
    @SerialName("av_sc_ao") val avScAo: String = "",
    @SerialName("av_sc_ao_cerca") val avScAoCerca: String = "",
    @SerialName("av_cc_od_lejos") val avCcOdLejos: String = "",
    @SerialName("av_cc_oi_lejos") val avCcOiLejos: String = "",
    @SerialName("av_cc_od_cerca") val avCcOdCerca: String = "",
    @SerialName("av_cc_oi_cerca") val avCcOiCerca: String = "",
    @SerialName("av_cc_ao_px") val avCcAoPx: String = "",
    @SerialName("av_cc_ao_cerca") val avCcAoCerca: String = "",

    // Motor
    @SerialName("ph_od") val phOd: String = "",
    @SerialName("ph_oi") val phOi: String = "",
    @SerialName("kappa_od") val kappaOd: String = "",
    @SerialName("kappa_oi") val kappaOi: String = "",
    val hirshberg: String = "",
    @SerialName("ducciones_od") val duccionesOd: String = "",
    @SerialName("ducciones_oi") val duccionesOi: String = "",
    @SerialName("versiones_ao") val versionesAo: String = "",
    @SerialName("estereopsis_valor") val estereopsisValor: String = "",
    @SerialName("estereopsis_segundos") val estereopsisSegundos: String = "",
    val lang: String = "",
    val worth: String = "",
    val ishihara: String = "",
    val farnsworth: String = "",
    @SerialName("schirmer_od") val schirmerOd: String = "",
    @SerialName("schirmer_oi") val schirmerOi: String = "",
    @SerialName("osdi_puntuacion") val osdiPuntuacion: Int? = null,
    @SerialName("osdi_clasificacion") val osdiClasificacion: String = "",
    @SerialName("sensibilidad_contraste") val sensibilidadContraste: String = "",
    @SerialName("sensibilidad_frecuencia") val sensibilidadFrecuencia: String = "",
    val amsler: String = "",
    @SerialName("campo_visual") val campoVisual: String = "",
    @SerialName("campo_visual_descripcion") val campoVisualDescripcion: String = "",
    @SerialName("cover_test_6m") val coverTest6m: String = "",
    @SerialName("cover_test_40cm") val coverTest40cm: String = "",
    @SerialName("cover_test_10cm") val coverTest10cm: String = "",
    @SerialName("ppc_or") val ppcOr: String = "",
    @SerialName("ppc_luz") val ppcLuz: String = "",
    @SerialName("ppc_frl") val ppcFrl: String = "",
    @SerialName("reflejo_fotomotor") val reflejoFotomotor: String = "",
    @SerialName("reflejo_consensual") val reflejoConsensual: String = "",
    @SerialName("reflejo_acomodativo") val reflejoAcomodativo: String = "",

    // Refracción
    @SerialName("k1_od") val k1Od: String = "",
    @SerialName("k2_od") val k2Od: String = "",
    @SerialName("k1_oi") val k1Oi: String = "",
    @SerialName("k2_oi") val k2Oi: String = "",
    @SerialName("obj_od_esf") val objOdEsf: String = "",
    @SerialName("obj_od_cil") val objOdCil: String = "",
    @SerialName("obj_od_eje") val objOdEje: String = "",
    @SerialName("obj_oi_esf") val objOiEsf: String = "",
    @SerialName("obj_oi_cil") val objOiCil: String = "",
    @SerialName("obj_oi_eje") val objOiEje: String = "",
    @SerialName("subj_od_esf") val subjOdEsf: String = "",
    @SerialName("subj_od_cil") val subjOdCil: String = "",
    @SerialName("subj_od_eje") val subjOdEje: String = "",
    @SerialName("subj_oi_esf") val subjOiEsf: String = "",
    @SerialName("subj_oi_cil") val subjOiCil: String = "",
    @SerialName("subj_oi_eje") val subjOiEje: String = "",
    @SerialName("receta_od_esf") val recetaOdEsf: String = "",
    @SerialName("receta_od_cil") val recetaOdCil: String = "",
    @SerialName("receta_od_eje") val recetaOdEje: String = "",
    @SerialName("receta_od_av") val recetaOdAv: String = "",
    @SerialName("receta_oi_esf") val recetaOiEsf: String = "",
    @SerialName("receta_oi_cil") val recetaOiCil: String = "",
    @SerialName("receta_oi_eje") val recetaOiEje: String = "",
    @SerialName("receta_oi_av") val recetaOiAv: String = "",
    @SerialName("add_cerca_od") val addCercaOd: String = "",
    @SerialName("add_cerca_oi") val addCercaOi: String = "",
    @SerialName("add_intermedia_od") val addIntermediaOd: String = "",
    @SerialName("add_intermedia_oi") val addIntermediaOi: String = "",
    @SerialName("add_av") val addAv: String = "",
    @SerialName("dip_lejos") val dipLejos: String = "",
    @SerialName("dip_cerca") val dipCerca: String = "",
    @SerialName("dip_intermedio") val dipIntermedio: String = "",
    @SerialName("dip_total_mm") val dipTotalMm: Double? = null,
    @SerialName("dnp_od_mm") val dnpOdMm: Double? = null,
    @SerialName("dnp_oi_mm") val dnpOiMm: Double? = null,
    @SerialName("prisma_od_valor") val prismaOdValor: String = "",
    @SerialName("prisma_od_base") val prismaOdBase: String = "",
    @SerialName("prisma_oi_valor") val prismaOiValor: String = "",
    @SerialName("prisma_oi_base") val prismaOiBase: String = "",

    // Diagnóstico
    val diagnostico: String = "",
    @SerialName("diagnostico_od") val diagnosticoOd: String = "",
    @SerialName("diagnostico_oi") val diagnosticoOi: String = "",
    @SerialName("diagnostico_otros") val diagnosticoOtros: String = "",
    @SerialName("plan_tratamiento") val planTratamiento: String = "",
    val observaciones: String = "",
    @SerialName("proxima_fecha_control") val proximaFechaControl: String? = null,
    @SerialName("proxima_cita") val proximaCita: String? = null,
    @SerialName("cita_estado") val citaEstado: String = "programada",
    @SerialName("balance_od") val balanceOd: Boolean = false,
    @SerialName("balance_oi") val balanceOi: Boolean = false,
    @SerialName("otros_presbicia") val otrosPresbicia: Boolean = false,
    @SerialName("otros_anisometropia") val otrosAnisometropia: Boolean = false,
    @SerialName("otros_ambliopia") val otrosAmbliopia: Boolean = false,
    @SerialName("auto_presbicia") val autoPresbicia: Boolean = true,
    @SerialName("auto_anisometropia") val autoAnisometropia: Boolean = true,
    @SerialName("auto_ambliopia") val autoAmbliopia: Boolean = true,

    // Contactología
    @SerialName("lc_od_esf") val lcOdEsf: String = "",
    @SerialName("lc_od_cil") val lcOdCil: String = "",
    @SerialName("lc_od_eje") val lcOdEje: String = "",
    @SerialName("lc_oi_esf") val lcOiEsf: String = "",
    @SerialName("lc_oi_cil") val lcOiCil: String = "",
    @SerialName("lc_oi_eje") val lcOiEje: String = "",
    @SerialName("lc_radio_base_od") val lcRadioBaseOd: String = "",
    @SerialName("lc_diametro_od") val lcDiametroOd: String = "",
    @SerialName("lc_radio_base_oi") val lcRadioBaseOi: String = "",
    @SerialName("lc_diametro_oi") val lcDiametroOi: String = "",
    @SerialName("lc_laboratorio") val lcLaboratorio: String = "",
    @SerialName("lc_tipo_lente") val lcTipoLente: String = "",
    @SerialName("lc_material") val lcMaterial: String = "",
    @SerialName("lc_fecha_adaptacion") val lcFechaAdaptacion: String? = null,
    @SerialName("lc_observaciones") val lcObservaciones: String = "",
    @SerialName("updated_at") val updatedAt: String? = null,
    @SerialName("updated_by") val updatedBy: String? = null
) {
    fun toEntity(): EvaluacionClinica = EvaluacionClinica(
        id = id, pacienteId = pacienteId, fecha = LocalDate.parse(fecha), opticaId = opticaId.ifBlank { "mi_optica_base" },
        motivoConsulta = motivoConsulta, sintomas = sintomas,
        antecedentesPersonalesOculares = antecedentesPersonalesOculares,
        antecedentesPersonalesSistemicos = antecedentesPersonalesSistemicos,
        antecedentesFamiliaresOculares = antecedentesFamiliaresOculares,
        antecedentesFamiliaresSistemicos = antecedentesFamiliaresSistemicos,
        medicacion = medicacion, alergias = alergias,
        necesidadVisual = necesidadVisual.split(",").filter { it.isNotBlank() },
        avScOdLejos = avScOdLejos, avScOiLejos = avScOiLejos,
        avScOdCerca = avScOdCerca, avScOiCerca = avScOiCerca,
        avScAo = avScAo, avScAoCerca = avScAoCerca,
        avCcOdLejos = avCcOdLejos, avCcOiLejos = avCcOiLejos,
        avCcOdCerca = avCcOdCerca, avCcOiCerca = avCcOiCerca,
        avCcAoPx = avCcAoPx, avCcAoCerca = avCcAoCerca,
        phOd = phOd, phOi = phOi, kappaOd = kappaOd, kappaOi = kappaOi,
        hirshberg = hirshberg, duccionesOd = duccionesOd, duccionesOi = duccionesOi, versionesAo = versionesAo,
        estereopsisValor = estereopsisValor, estereopsisSegundos = estereopsisSegundos,
        lang = lang, worth = worth, ishihara = ishihara, farnsworth = farnsworth,
        schirmerOd = schirmerOd, schirmerOi = schirmerOi,
        osdiPuntuacion = osdiPuntuacion, osdiClasificacion = osdiClasificacion,
        sensibilidadContraste = sensibilidadContraste, sensibilidadFrecuencia = sensibilidadFrecuencia,
        amsler = amsler, campoVisual = campoVisual, campoVisualDescripcion = campoVisualDescripcion,
        coverTest6m = coverTest6m, coverTest40cm = coverTest40cm, coverTest10cm = coverTest10cm,
        ppcOr = ppcOr, ppcLuz = ppcLuz, ppcFrl = ppcFrl,
        reflejoFotomotor = reflejoFotomotor, reflejoConsensual = reflejoConsensual, reflejoAcomodativo = reflejoAcomodativo,
        k1Od = k1Od, k2Od = k2Od, k1Oi = k1Oi, k2Oi = k2Oi,
        objOdEsf = objOdEsf, objOdCil = objOdCil, objOdEje = objOdEje,
        objOiEsf = objOiEsf, objOiCil = objOiCil, objOiEje = objOiEje,
        subjOdEsf = subjOdEsf, subjOdCil = subjOdCil, subjOdEje = subjOdEje,
        subjOiEsf = subjOiEsf, subjOiCil = subjOiCil, subjOiEje = subjOiEje,
        recetaOdEsf = recetaOdEsf, recetaOdCil = recetaOdCil, recetaOdEje = recetaOdEje, recetaOdAv = recetaOdAv,
        recetaOiEsf = recetaOiEsf, recetaOiCil = recetaOiCil, recetaOiEje = recetaOiEje, recetaOiAv = recetaOiAv,
        addCercaOd = addCercaOd, addCercaOi = addCercaOi,
        addIntermediaOd = addIntermediaOd, addIntermediaOi = addIntermediaOi,
        addAv = addAv,
        dipLejos = dipLejos, dipCerca = dipCerca, dipIntermedio = dipIntermedio,
        dipTotalMm = dipTotalMm, dnpOdMm = dnpOdMm, dnpOiMm = dnpOiMm,
        prismaOdValor = prismaOdValor, prismaOdBase = prismaOdBase,
        prismaOiValor = prismaOiValor, prismaOiBase = prismaOiBase,
        diagnostico = diagnostico,
        diagnosticoOd = diagnosticoOd.split(",").filter { it.isNotBlank() },
        diagnosticoOi = diagnosticoOi.split(",").filter { it.isNotBlank() },
        diagnosticoOtros = diagnosticoOtros.split(",").filter { it.isNotBlank() },
        planTratamiento = planTratamiento, observaciones = observaciones,
        proximaFechaControl = proximaFechaControl.orEmpty(),
        proximaCita = proximaCita?.trim()?.takeIf { it.isNotEmpty() }?.let(LocalDate::parse),
        citaEstado = citaEstado.trim().ifBlank { "programada" },
        balanceOd = balanceOd, balanceOi = balanceOi,
        otrosPresbicia = otrosPresbicia, otrosAnisometropia = otrosAnisometropia, otrosAmbliopia = otrosAmbliopia,
        autoPresbicia = autoPresbicia, autoAnisometropia = autoAnisometropia, autoAmbliopia = autoAmbliopia,
        lcOdEsf = lcOdEsf, lcOdCil = lcOdCil, lcOdEje = lcOdEje,
        lcOiEsf = lcOiEsf, lcOiCil = lcOiCil, lcOiEje = lcOiEje,
        lcRadioBaseOd = lcRadioBaseOd, lcDiametroOd = lcDiametroOd,
        lcRadioBaseOi = lcRadioBaseOi, lcDiametroOi = lcDiametroOi,
        lcLaboratorio = lcLaboratorio, lcTipoLente = lcTipoLente,
        lcMaterial = lcMaterial,
        lcFechaAdaptacion = lcFechaAdaptacion?.trim()?.takeIf { it.isNotEmpty() }?.let(LocalDate::parse),
        lcObservaciones = lcObservaciones,
        updatedAt = updatedAt,
        updatedBy = updatedBy
    )
}

fun EvaluacionClinica.toRemoto(): EvaluacionRemota = EvaluacionRemota(
    id = id, pacienteId = pacienteId, fecha = fecha.toString(), opticaId = opticaId,
    motivoConsulta = motivoConsulta, sintomas = sintomas,
    antecedentesPersonalesOculares = antecedentesPersonalesOculares,
    antecedentesPersonalesSistemicos = antecedentesPersonalesSistemicos,
    antecedentesFamiliaresOculares = antecedentesFamiliaresOculares,
    antecedentesFamiliaresSistemicos = antecedentesFamiliaresSistemicos,
    medicacion = medicacion, alergias = alergias,
    necesidadVisual = necesidadVisual.joinToString(","),
    avScOdLejos = avScOdLejos, avScOiLejos = avScOiLejos,
    avScOdCerca = avScOdCerca, avScOiCerca = avScOiCerca,
    avScAo = avScAo, avScAoCerca = avScAoCerca,
    avCcOdLejos = avCcOdLejos, avCcOiLejos = avCcOiLejos,
    avCcOdCerca = avCcOdCerca, avCcOiCerca = avCcOiCerca,
    avCcAoPx = avCcAoPx, avCcAoCerca = avCcAoCerca,
    phOd = phOd, phOi = phOi, kappaOd = kappaOd, kappaOi = kappaOi,
    hirshberg = hirshberg, duccionesOd = duccionesOd, duccionesOi = duccionesOi, versionesAo = versionesAo,
    estereopsisValor = estereopsisValor, estereopsisSegundos = estereopsisSegundos,
    lang = lang, worth = worth, ishihara = ishihara, farnsworth = farnsworth,
    schirmerOd = schirmerOd, schirmerOi = schirmerOi,
    osdiPuntuacion = osdiPuntuacion, osdiClasificacion = osdiClasificacion,
    sensibilidadContraste = sensibilidadContraste, sensibilidadFrecuencia = sensibilidadFrecuencia,
    amsler = amsler, campoVisual = campoVisual, campoVisualDescripcion = campoVisualDescripcion,
    coverTest6m = coverTest6m, coverTest40cm = coverTest40cm, coverTest10cm = coverTest10cm,
    ppcOr = ppcOr, ppcLuz = ppcLuz, ppcFrl = ppcFrl,
    reflejoFotomotor = reflejoFotomotor, reflejoConsensual = reflejoConsensual, reflejoAcomodativo = reflejoAcomodativo,
    k1Od = k1Od, k2Od = k2Od, k1Oi = k1Oi, k2Oi = k2Oi,
    objOdEsf = objOdEsf, objOdCil = objOdCil, objOdEje = objOdEje,
    objOiEsf = objOiEsf, objOiCil = objOiCil, objOiEje = objOiEje,
    subjOdEsf = subjOdEsf, subjOdCil = subjOdCil, subjOdEje = subjOdEje,
    subjOiEsf = subjOiEsf, subjOiCil = subjOiCil, subjOiEje = subjOiEje,
    recetaOdEsf = recetaOdEsf, recetaOdCil = recetaOdCil, recetaOdEje = recetaOdEje, recetaOdAv = recetaOdAv,
    recetaOiEsf = recetaOiEsf, recetaOiCil = recetaOiCil, recetaOiEje = recetaOiEje, recetaOiAv = recetaOiAv,
    addCercaOd = addCercaOd, addCercaOi = addCercaOi,
    addIntermediaOd = addIntermediaOd, addIntermediaOi = addIntermediaOi,
    addAv = addAv,
    dipLejos = dipLejos, dipCerca = dipCerca, dipIntermedio = dipIntermedio,
    dipTotalMm = dipTotalMm, dnpOdMm = dnpOdMm, dnpOiMm = dnpOiMm,
    prismaOdValor = prismaOdValor, prismaOdBase = prismaOdBase,
    prismaOiValor = prismaOiValor, prismaOiBase = prismaOiBase,
    diagnostico = diagnostico,
    diagnosticoOd = diagnosticoOd.joinToString(","),
    diagnosticoOi = diagnosticoOi.joinToString(","),
    diagnosticoOtros = diagnosticoOtros.joinToString(","),
    planTratamiento = planTratamiento, observaciones = observaciones,
    proximaFechaControl = proximaFechaControl.trim().ifBlank { null }, proximaCita = proximaCita?.toString(),
    citaEstado = citaEstado.trim().ifBlank { "programada" },
    balanceOd = balanceOd, balanceOi = balanceOi,
    otrosPresbicia = otrosPresbicia, otrosAnisometropia = otrosAnisometropia, otrosAmbliopia = otrosAmbliopia,
    autoPresbicia = autoPresbicia, autoAnisometropia = autoAnisometropia, autoAmbliopia = autoAmbliopia,
    lcOdEsf = lcOdEsf, lcOdCil = lcOdCil, lcOdEje = lcOdEje,
    lcOiEsf = lcOiEsf, lcOiCil = lcOiCil, lcOiEje = lcOiEje,
    lcRadioBaseOd = lcRadioBaseOd, lcDiametroOd = lcDiametroOd,
    lcRadioBaseOi = lcRadioBaseOi, lcDiametroOi = lcDiametroOi,
    lcLaboratorio = lcLaboratorio, lcTipoLente = lcTipoLente,
    lcMaterial = lcMaterial, lcFechaAdaptacion = lcFechaAdaptacion?.toString(),
    lcObservaciones = lcObservaciones,
    updatedAt = updatedAt ?: Instant.now().toString(),
    updatedBy = updatedBy
)
