package com.example.optoapp.domain

import com.example.optoapp.data.EvaluacionClinica
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.time.LocalDate

data class HistorialSyncResult(val uploaded: Int, val downloaded: Int)

@Serializable
data class EvaluacionRemota(
    val id: String,
    @SerialName("paciente_id") val pacienteId: String,
    val fecha: String,
    @SerialName("optica_id") val opticaId: String,
    @SerialName("motivo_consulta") val motivoConsulta: String? = null,
    val sintomas: String? = null,
    @SerialName("antecedentes_personales_oculares") val antecedentesPersonalesOculares: String? = null,
    @SerialName("antecedentes_personales_sistemicos") val antecedentesPersonalesSistemicos: String? = null,
    @SerialName("antecedentes_familiares_oculares") val antecedentesFamiliaresOculares: String? = null,
    @SerialName("antecedentes_familiares_sistemicos") val antecedentesFamiliaresSistemicos: String? = null,
    val medicacion: String? = null,
    val alergias: String? = null,
    @SerialName("necesidad_visual") val necesidadVisual: String? = null,

    // AV
    @SerialName("av_sc_od_lejos") val avScOdLejos: String? = null,
    @SerialName("av_sc_oi_lejos") val avScOiLejos: String? = null,
    @SerialName("av_sc_od_cerca") val avScOdCerca: String? = null,
    @SerialName("av_sc_oi_cerca") val avScOiCerca: String? = null,
    @SerialName("av_sc_ao") val avScAo: String? = null,
    @SerialName("av_sc_ao_cerca") val avScAoCerca: String? = null,
    @SerialName("av_cc_od_lejos") val avCcOdLejos: String? = null,
    @SerialName("av_cc_oi_lejos") val avCcOiLejos: String? = null,
    @SerialName("av_cc_od_cerca") val avCcOdCerca: String? = null,
    @SerialName("av_cc_oi_cerca") val avCcOiCerca: String? = null,
    @SerialName("av_cc_ao_px") val avCcAoPx: String? = null,
    @SerialName("av_cc_ao_cerca") val avCcAoCerca: String? = null,

    // Motor
    @SerialName("ph_od") val phOd: String? = null,
    @SerialName("ph_oi") val phOi: String? = null,
    @SerialName("kappa_od") val kappaOd: String? = null,
    @SerialName("kappa_oi") val kappaOi: String? = null,
    val hirshberg: String? = null,
    @SerialName("ducciones_od") val duccionesOd: String? = null,
    @SerialName("ducciones_oi") val duccionesOi: String? = null,
    @SerialName("versiones_ao") val versionesAo: String? = null,
    @SerialName("estereopsis_valor") val estereopsisValor: String? = null,
    @SerialName("estereopsis_segundos") val estereopsisSegundos: String? = null,
    val lang: String? = null,
    val worth: String? = null,
    val ishihara: String? = null,
    val farnsworth: String? = null,
    @SerialName("schirmer_od") val schirmerOd: String? = null,
    @SerialName("schirmer_oi") val schirmerOi: String? = null,
    @SerialName("osdi_puntuacion") val osdiPuntuacion: Int? = null,
    @SerialName("osdi_clasificacion") val osdiClasificacion: String? = null,
    @SerialName("sensibilidad_contraste") val sensibilidadContraste: String? = null,
    @SerialName("sensibilidad_frecuencia") val sensibilidadFrecuencia: String? = null,
    val amsler: String? = null,
    @SerialName("campo_visual") val campoVisual: String? = null,
    @SerialName("campo_visual_descripcion") val campoVisualDescripcion: String? = null,
    @SerialName("cover_test_6m") val coverTest6m: String? = null,
    @SerialName("cover_test_40cm") val coverTest40cm: String? = null,
    @SerialName("cover_test_10cm") val coverTest10cm: String? = null,
    @SerialName("ppc_or") val ppcOr: String? = null,
    @SerialName("ppc_luz") val ppcLuz: String? = null,
    @SerialName("ppc_frl") val ppcFrl: String? = null,
    @SerialName("reflejo_fotomotor") val reflejoFotomotor: String? = null,
    @SerialName("reflejo_consensual") val reflejoConsensual: String? = null,
    @SerialName("reflejo_acomodativo") val reflejoAcomodativo: String? = null,

    // Refracción
    @SerialName("k1_od") val k1Od: String? = null,
    @SerialName("k2_od") val k2Od: String? = null,
    @SerialName("k1_oi") val k1Oi: String? = null,
    @SerialName("k2_oi") val k2Oi: String? = null,
    @SerialName("obj_od_esf") val objOdEsf: String? = null,
    @SerialName("obj_od_cil") val objOdCil: String? = null,
    @SerialName("obj_od_eje") val objOdEje: String? = null,
    @SerialName("obj_oi_esf") val objOiEsf: String? = null,
    @SerialName("obj_oi_cil") val objOiCil: String? = null,
    @SerialName("obj_oi_eje") val objOiEje: String? = null,
    @SerialName("subj_od_esf") val subjOdEsf: String? = null,
    @SerialName("subj_od_cil") val subjOdCil: String? = null,
    @SerialName("subj_od_eje") val subjOdEje: String? = null,
    @SerialName("subj_oi_esf") val subjOiEsf: String? = null,
    @SerialName("subj_oi_cil") val subjOiCil: String? = null,
    @SerialName("subj_oi_eje") val subjOiEje: String? = null,
    @SerialName("receta_od_esf") val recetaOdEsf: String? = null,
    @SerialName("receta_od_cil") val recetaOdCil: String? = null,
    @SerialName("receta_od_eje") val recetaOdEje: String? = null,
    @SerialName("receta_od_av") val recetaOdAv: String? = null,
    @SerialName("receta_oi_esf") val recetaOiEsf: String? = null,
    @SerialName("receta_oi_cil") val recetaOiCil: String? = null,
    @SerialName("receta_oi_eje") val recetaOiEje: String? = null,
    @SerialName("receta_oi_av") val recetaOiAv: String? = null,
    @SerialName("add_cerca_od") val addCercaOd: String? = null,
    @SerialName("add_cerca_oi") val addCercaOi: String? = null,
    @SerialName("add_intermedia_od") val addIntermediaOd: String? = null,
    @SerialName("add_intermedia_oi") val addIntermediaOi: String? = null,
    @SerialName("add_av") val addAv: String? = null,
    @SerialName("dip_lejos") val dipLejos: String? = null,
    @SerialName("dip_cerca") val dipCerca: String? = null,
    @SerialName("dip_intermedio") val dipIntermedio: String? = null,
    @SerialName("dip_total_mm") val dipTotalMm: Double? = null,
    @SerialName("dnp_od_mm") val dnpOdMm: Double? = null,
    @SerialName("dnp_oi_mm") val dnpOiMm: Double? = null,
    @SerialName("prisma_od_valor") val prismaOdValor: String? = null,
    @SerialName("prisma_od_base") val prismaOdBase: String? = null,
    @SerialName("prisma_oi_valor") val prismaOiValor: String? = null,
    @SerialName("prisma_oi_base") val prismaOiBase: String? = null,

    // Diagnóstico
    val diagnostico: String? = null,
    @SerialName("diagnostico_od") val diagnosticoOd: String? = null,
    @SerialName("diagnostico_oi") val diagnosticoOi: String? = null,
    @SerialName("diagnostico_otros") val diagnosticoOtros: String? = null,
    @SerialName("plan_tratamiento") val planTratamiento: String? = null,
    val observaciones: String? = null,
    @SerialName("proxima_fecha_control") val proximaFechaControl: String? = null,
    @SerialName("proxima_cita") val proximaCita: String? = null,
    @SerialName("cita_estado") val citaEstado: String? = null,
    @SerialName("balance_od") val balanceOd: Boolean = false,
    @SerialName("balance_oi") val balanceOi: Boolean = false,
    @SerialName("otros_presbicia") val otrosPresbicia: Boolean = false,
    @SerialName("otros_anisometropia") val otrosAnisometropia: Boolean = false,
    @SerialName("otros_ambliopia") val otrosAmbliopia: Boolean = false,
    @SerialName("auto_presbicia") val autoPresbicia: Boolean = true,
    @SerialName("auto_anisometropia") val autoAnisometropia: Boolean = true,
    @SerialName("auto_ambliopia") val autoAmbliopia: Boolean = true,

    // Contactología
    @SerialName("lc_od_esf") val lcOdEsf: String? = null,
    @SerialName("lc_od_cil") val lcOdCil: String? = null,
    @SerialName("lc_od_eje") val lcOdEje: String? = null,
    @SerialName("lc_oi_esf") val lcOiEsf: String? = null,
    @SerialName("lc_oi_cil") val lcOiCil: String? = null,
    @SerialName("lc_oi_eje") val lcOiEje: String? = null,
    @SerialName("lc_radio_base_od") val lcRadioBaseOd: String? = null,
    @SerialName("lc_diametro_od") val lcDiametroOd: String? = null,
    @SerialName("lc_radio_base_oi") val lcRadioBaseOi: String? = null,
    @SerialName("lc_diametro_oi") val lcDiametroOi: String? = null,
    @SerialName("lc_laboratorio") val lcLaboratorio: String? = null,
    @SerialName("lc_tipo_lente") val lcTipoLente: String? = null,
    @SerialName("lc_material") val lcMaterial: String? = null,
    @SerialName("lc_fecha_adaptacion") val lcFechaAdaptacion: String? = null,
    @SerialName("lc_observaciones") val lcObservaciones: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null,
    @SerialName("updated_by") val updatedBy: String? = null
) {
    fun toEntity(): EvaluacionClinica = EvaluacionClinica(
        id = id, pacienteId = pacienteId, fecha = LocalDate.parse(fecha), opticaId = opticaId.ifBlank { "mi_optica_base" },
        motivoConsulta = motivoConsulta.orEmpty(), sintomas = sintomas.orEmpty(),
        antecedentesPersonalesOculares = antecedentesPersonalesOculares.orEmpty(),
        antecedentesPersonalesSistemicos = antecedentesPersonalesSistemicos.orEmpty(),
        antecedentesFamiliaresOculares = antecedentesFamiliaresOculares.orEmpty(),
        antecedentesFamiliaresSistemicos = antecedentesFamiliaresSistemicos.orEmpty(),
        medicacion = medicacion.orEmpty(), alergias = alergias.orEmpty(),
        necesidadVisual = necesidadVisual.orEmpty().split(",").filter { it.isNotBlank() },
        avScOdLejos = avScOdLejos.orEmpty(), avScOiLejos = avScOiLejos.orEmpty(),
        avScOdCerca = avScOdCerca.orEmpty(), avScOiCerca = avScOiCerca.orEmpty(),
        avScAo = avScAo.orEmpty(), avScAoCerca = avScAoCerca.orEmpty(),
        avCcOdLejos = avCcOdLejos.orEmpty(), avCcOiLejos = avCcOiLejos.orEmpty(),
        avCcOdCerca = avCcOdCerca.orEmpty(), avCcOiCerca = avCcOiCerca.orEmpty(),
        avCcAoPx = avCcAoPx.orEmpty(), avCcAoCerca = avCcAoCerca.orEmpty(),
        phOd = phOd.orEmpty(), phOi = phOi.orEmpty(), kappaOd = kappaOd.orEmpty(), kappaOi = kappaOi.orEmpty(),
        hirshberg = hirshberg.orEmpty(), duccionesOd = duccionesOd.orEmpty(), duccionesOi = duccionesOi.orEmpty(), versionesAo = versionesAo.orEmpty(),
        estereopsisValor = estereopsisValor.orEmpty(), estereopsisSegundos = estereopsisSegundos.orEmpty(),
        lang = lang.orEmpty(), worth = worth.orEmpty(), ishihara = ishihara.orEmpty(), farnsworth = farnsworth.orEmpty(),
        schirmerOd = schirmerOd.orEmpty(), schirmerOi = schirmerOi.orEmpty(),
        osdiPuntuacion = osdiPuntuacion, osdiClasificacion = osdiClasificacion.orEmpty(),
        sensibilidadContraste = sensibilidadContraste.orEmpty(), sensibilidadFrecuencia = sensibilidadFrecuencia.orEmpty(),
        amsler = amsler.orEmpty(), campoVisual = campoVisual.orEmpty(), campoVisualDescripcion = campoVisualDescripcion.orEmpty(),
        coverTest6m = coverTest6m.orEmpty(), coverTest40cm = coverTest40cm.orEmpty(), coverTest10cm = coverTest10cm.orEmpty(),
        ppcOr = ppcOr.orEmpty(), ppcLuz = ppcLuz.orEmpty(), ppcFrl = ppcFrl.orEmpty(),
        reflejoFotomotor = reflejoFotomotor.orEmpty(), reflejoConsensual = reflejoConsensual.orEmpty(), reflejoAcomodativo = reflejoAcomodativo.orEmpty(),
        k1Od = k1Od.orEmpty(), k2Od = k2Od.orEmpty(), k1Oi = k1Oi.orEmpty(), k2Oi = k2Oi.orEmpty(),
        objOdEsf = objOdEsf.orEmpty(), objOdCil = objOdCil.orEmpty(), objOdEje = objOdEje.orEmpty(),
        objOiEsf = objOiEsf.orEmpty(), objOiCil = objOiCil.orEmpty(), objOiEje = objOiEje.orEmpty(),
        subjOdEsf = subjOdEsf.orEmpty(), subjOdCil = subjOdCil.orEmpty(), subjOdEje = subjOdEje.orEmpty(),
        subjOiEsf = subjOiEsf.orEmpty(), subjOiCil = subjOiCil.orEmpty(), subjOiEje = subjOiEje.orEmpty(),
        recetaOdEsf = recetaOdEsf.orEmpty(), recetaOdCil = recetaOdCil.orEmpty(), recetaOdEje = recetaOdEje.orEmpty(), recetaOdAv = recetaOdAv.orEmpty(),
        recetaOiEsf = recetaOiEsf.orEmpty(), recetaOiCil = recetaOiCil.orEmpty(), recetaOiEje = recetaOiEje.orEmpty(), recetaOiAv = recetaOiAv.orEmpty(),
        addCercaOd = addCercaOd.orEmpty(), addCercaOi = addCercaOi.orEmpty(),
        addIntermediaOd = addIntermediaOd.orEmpty(), addIntermediaOi = addIntermediaOi.orEmpty(),
        addAv = addAv.orEmpty(),
        dipLejos = dipLejos.orEmpty(), dipCerca = dipCerca.orEmpty(), dipIntermedio = dipIntermedio.orEmpty(),
        dipTotalMm = dipTotalMm, dnpOdMm = dnpOdMm, dnpOiMm = dnpOiMm,
        prismaOdValor = prismaOdValor.orEmpty(), prismaOdBase = prismaOdBase.orEmpty(),
        prismaOiValor = prismaOiValor.orEmpty(), prismaOiBase = prismaOiBase.orEmpty(),
        diagnostico = diagnostico.orEmpty(),
        diagnosticoOd = diagnosticoOd.orEmpty().split(",").filter { it.isNotBlank() },
        diagnosticoOi = diagnosticoOi.orEmpty().split(",").filter { it.isNotBlank() },
        diagnosticoOtros = diagnosticoOtros.orEmpty().split(",").filter { it.isNotBlank() },
        planTratamiento = planTratamiento.orEmpty(), observaciones = observaciones.orEmpty(),
        proximaFechaControl = proximaFechaControl.orEmpty(),
        proximaCita = proximaCita?.trim()?.takeIf { it.isNotEmpty() }?.let(LocalDate::parse),
        citaEstado = citaEstado?.trim().orEmpty().ifBlank { "programada" },
        balanceOd = balanceOd, balanceOi = balanceOi,
        otrosPresbicia = otrosPresbicia, otrosAnisometropia = otrosAnisometropia, otrosAmbliopia = otrosAmbliopia,
        autoPresbicia = autoPresbicia, autoAnisometropia = autoAnisometropia, autoAmbliopia = autoAmbliopia,
        lcOdEsf = lcOdEsf.orEmpty(), lcOdCil = lcOdCil.orEmpty(), lcOdEje = lcOdEje.orEmpty(),
        lcOiEsf = lcOiEsf.orEmpty(), lcOiCil = lcOiCil.orEmpty(), lcOiEje = lcOiEje.orEmpty(),
        lcRadioBaseOd = lcRadioBaseOd.orEmpty(), lcDiametroOd = lcDiametroOd.orEmpty(),
        lcRadioBaseOi = lcRadioBaseOi.orEmpty(), lcDiametroOi = lcDiametroOi.orEmpty(),
        lcLaboratorio = lcLaboratorio.orEmpty(), lcTipoLente = lcTipoLente.orEmpty(),
        lcMaterial = lcMaterial.orEmpty(),
        lcFechaAdaptacion = lcFechaAdaptacion?.trim()?.takeIf { it.isNotEmpty() }?.let(LocalDate::parse),
        lcObservaciones = lcObservaciones.orEmpty(),
        updatedAt = updatedAt,
        updatedBy = updatedBy
    )
}

fun EvaluacionClinica.toRemoto(): EvaluacionRemota = EvaluacionRemota(
    id = id, pacienteId = pacienteId, fecha = fecha.toString(), opticaId = opticaId,
    motivoConsulta = motivoConsulta, sintomas = sintomas,
    antecedentesPersonalesOculares = antecedentesPersonalesOculares,
    antecedentesPersonalesSistemicos = antecedentesPersonalesSistemicos,
    antecedentesFamiliaresOculares = antecedentesFamiliaresOculares,
    antecedentesFamiliaresSistemicos = antecedentesFamiliaresSistemicos,
    medicacion = medicacion, alergias = alergias,
    necesidadVisual = necesidadVisual.joinToString(","),
    avScOdLejos = avScOdLejos, avScOiLejos = avScOiLejos,
    avScOdCerca = avScOdCerca, avScOiCerca = avScOiCerca,
    avScAo = avScAo, avScAoCerca = avScAoCerca,
    avCcOdLejos = avCcOdLejos, avCcOiLejos = avCcOiLejos,
    avCcOdCerca = avCcOdCerca, avCcOiCerca = avCcOiCerca,
    avCcAoPx = avCcAoPx, avCcAoCerca = avCcAoCerca,
    phOd = phOd, phOi = phOi, kappaOd = kappaOd, kappaOi = kappaOi,
    hirshberg = hirshberg, duccionesOd = duccionesOd, duccionesOi = duccionesOi, versionesAo = versionesAo,
    estereopsisValor = estereopsisValor, estereopsisSegundos = estereopsisSegundos,
    lang = lang, worth = worth, ishihara = ishihara, farnsworth = farnsworth,
    schirmerOd = schirmerOd, schirmerOi = schirmerOi,
    osdiPuntuacion = osdiPuntuacion, osdiClasificacion = osdiClasificacion,
    sensibilidadContraste = sensibilidadContraste, sensibilidadFrecuencia = sensibilidadFrecuencia,
    amsler = amsler, campoVisual = campoVisual, campoVisualDescripcion = campoVisualDescripcion,
    coverTest6m = coverTest6m, coverTest40cm = coverTest40cm, coverTest10cm = coverTest10cm,
    ppcOr = ppcOr, ppcLuz = ppcLuz, ppcFrl = ppcFrl,
    reflejoFotomotor = reflejoFotomotor, reflejoConsensual = reflejoConsensual, reflejoAcomodativo = reflejoAcomodativo,
    k1Od = k1Od, k2Od = k2Od, k1Oi = k1Oi, k2Oi = k2Oi,
    objOdEsf = objOdEsf, objOdCil = objOdCil, objOdEje = objOdEje,
    objOiEsf = objOiEsf, objOiCil = objOiCil, objOiEje = objOiEje,
    subjOdEsf = subjOdEsf, subjOdCil = subjOdCil, subjOdEje = subjOdEje,
    subjOiEsf = subjOiEsf, subjOiCil = subjOiCil, subjOiEje = subjOiEje,
    recetaOdEsf = recetaOdEsf, recetaOdCil = recetaOdCil, recetaOdEje = recetaOdEje, recetaOdAv = recetaOdAv,
    recetaOiEsf = recetaOiEsf, recetaOiCil = recetaOiCil, recetaOiEje = recetaOiEje, recetaOiAv = recetaOiAv,
    addCercaOd = addCercaOd, addCercaOi = addCercaOi,
    addIntermediaOd = addIntermediaOd, addIntermediaOi = addIntermediaOi,
    addAv = addAv,
    dipLejos = dipLejos, dipCerca = dipCerca, dipIntermedio = dipIntermedio,
    dipTotalMm = dipTotalMm, dnpOdMm = dnpOdMm, dnpOiMm = dnpOiMm,
    prismaOdValor = prismaOdValor, prismaOdBase = prismaOdBase,
    prismaOiValor = prismaOiValor, prismaOiBase = prismaOiBase,
    diagnostico = diagnostico,
    diagnosticoOd = diagnosticoOd.joinToString(","),
    diagnosticoOi = diagnosticoOi.joinToString(","),
    diagnosticoOtros = diagnosticoOtros.joinToString(","),
    planTratamiento = planTratamiento, observaciones = observaciones,
    proximaFechaControl = proximaFechaControl.trim().ifBlank { null }, proximaCita = proximaCita?.toString(),
    citaEstado = citaEstado.trim().ifBlank { "programada" },
    balanceOd = balanceOd, balanceOi = balanceOi,
    otrosPresbicia = otrosPresbicia, otrosAnisometropia = otrosAnisometropia, otrosAmbliopia = otrosAmbliopia,
    autoPresbicia = autoPresbicia, autoAnisometropia = autoAnisometropia, autoAmbliopia = autoAmbliopia,
    lcOdEsf = lcOdEsf, lcOdCil = lcOdCil, lcOdEje = lcOdEje,
    lcOiEsf = lcOiEsf, lcOiCil = lcOiCil, lcOiEje = lcOiEje,
    lcRadioBaseOd = lcRadioBaseOd, lcDiametroOd = lcDiametroOd,
    lcRadioBaseOi = lcRadioBaseOi, lcDiametroOi = lcDiametroOi,
    lcLaboratorio = lcLaboratorio, lcTipoLente = lcTipoLente,
    lcMaterial = lcMaterial, lcFechaAdaptacion = lcFechaAdaptacion?.toString(),
    lcObservaciones = lcObservaciones,
    updatedAt = updatedAt,
    updatedBy = updatedBy
)
