package com.example.optoapp.viewmodel

import com.example.optoapp.data.EvaluacionClinica
import java.util.UUID

fun EvaluacionUiState.toEvaluacionClinica(
    evaluacionId: String?,
    pacienteId: String,
    opticaId: String,
    dipParsed: DipParseResult,
): EvaluacionClinica {
    val s = this
    return EvaluacionClinica(
        id = evaluacionId ?: UUID.randomUUID().toString(),
        pacienteId = pacienteId,
        fecha = s.fecha,
        opticaId = opticaId,
        motivoConsulta = s.motivoConsulta,
        sintomas = s.sintomas,
        antecedentesPersonalesOculares = s.antecedentesPersonalesOculares,
        antecedentesPersonalesSistemicos = s.antecedentesPersonalesSistemicos,
        antecedentesFamiliaresOculares = s.antecedentesFamiliaresOculares,
        antecedentesFamiliaresSistemicos = s.antecedentesFamiliaresSistemicos,
        medicacion = s.medicacion,
        alergias = s.alergias,
        necesidadVisual = s.necesidadVisual,
        avScOdLejos = s.avScOdLejos, avScOiLejos = s.avScOiLejos,
        avScOdCerca = s.avScOdCerca, avScOiCerca = s.avScOiCerca,
        avScAo = s.avScAo, avScAoCerca = s.avScAoCerca,
        avCcOdLejos = s.avCcOdLejos, avCcOiLejos = s.avCcOiLejos,
        avCcOdCerca = s.avCcOdCerca, avCcOiCerca = s.avCcOiCerca,
        avCcAoPx = s.avCcAoPx, avCcAoCerca = s.avCcAoCerca,
        phOd = s.phOd, phOi = s.phOi, kappaOd = s.kappaOd, kappaOi = s.kappaOi,
        hirshberg = s.hirshberg,
        duccionesOd = s.duccionesOd, duccionesOi = s.duccionesOi,
        versionesAo = s.versionesAo,
        estereopsisValor = s.estereopsisValor,
        estereopsisSegundos = s.estereopsisSegundos,
        lang = s.lang, worth = s.worth,
        ishihara = s.ishihara, farnsworth = s.farnsworth,
        schirmerOd = s.schirmerOd, schirmerOi = s.schirmerOi,
        osdiPuntuacion = s.osdiPuntuacion, osdiClasificacion = s.osdiClasificacion,
        sensibilidadContraste = s.sensibilidadContraste, sensibilidadFrecuencia = s.sensibilidadFrecuencia,
        amsler = s.amsler, campoVisual = s.campoVisual, campoVisualDescripcion = s.campoVisualDescripcion,
        coverTest6m = s.coverTest6m, coverTest40cm = s.coverTest40cm, coverTest10cm = s.coverTest10cm,
        ppcOr = s.ppcOr, ppcLuz = s.ppcLuz, ppcFrl = s.ppcFrl,
        reflejoFotomotor = s.reflejoFotomotor, reflejoConsensual = s.reflejoConsensual, reflejoAcomodativo = s.reflejoAcomodativo,
        k1Od = s.k1Od, k2Od = s.k2Od, k1Oi = s.k1Oi, k2Oi = s.k2Oi,
        objOdEsf = s.objOdEsf, objOdCil = s.objOdCil, objOdEje = s.objOdEje,
        objOiEsf = s.objOiEsf, objOiCil = s.objOiCil, objOiEje = s.objOiEje,
        subjOdEsf = s.subjOdEsf, subjOdCil = s.subjOdCil, subjOdEje = s.subjOdEje,
        subjOiEsf = s.subjOiEsf, subjOiCil = s.subjOiCil, subjOiEje = s.subjOiEje,
        recetaOdEsf = s.recetaOdEsf, recetaOdCil = s.recetaOdCil, recetaOdEje = s.recetaOdEje, recetaOdAv = s.recetaOdAv,
        recetaOiEsf = s.recetaOiEsf, recetaOiCil = s.recetaOiCil, recetaOiEje = s.recetaOiEje, recetaOiAv = s.recetaOiAv,
        addCercaOd = s.addCercaOd, addCercaOi = s.addCercaOi,
        addIntermediaOd = s.addIntermediaOd, addIntermediaOi = s.addIntermediaOi, addAv = s.addAv,
        dipLejos = s.dipLejos.trim(), dipCerca = s.dipCerca, dipIntermedio = s.dipIntermedio,
        dipTotalMm = dipParsed.dipTotalMm,
        dnpOdMm = dipParsed.dnpOdMm,
        dnpOiMm = dipParsed.dnpOiMm,
        prismaOdValor = s.prismaOdValor, prismaOdBase = s.prismaOdBase,
        prismaOiValor = s.prismaOiValor, prismaOiBase = s.prismaOiBase,
        diagnostico = s.diagnostico,
        diagnosticoOd = s.diagnosticoOd,
        diagnosticoOi = s.diagnosticoOi,
        diagnosticoOtros = s.diagnosticoOtros,
        planTratamiento = s.planTratamiento,
        observaciones = s.observaciones,
        proximaFechaControl = s.proximaFechaControl,
        proximaCita = s.proximaCita,
        citaEstado = s.citaEstado.trim().ifBlank { "programada" },
        balanceOd = s.balanceOd,
        balanceOi = s.balanceOi,
        otrosPresbicia = s.otrosPresbicia,
        otrosAnisometropia = s.otrosAnisometropia,
        otrosAmbliopia = s.otrosAmbliopia,
        autoPresbicia = s.autoPresbicia,
        autoAnisometropia = s.autoAnisometropia,
        autoAmbliopia = s.autoAmbliopia,
        lcOdEsf = s.lcOdEsf, lcOdCil = s.lcOdCil, lcOdEje = s.lcOdEje,
        lcOiEsf = s.lcOiEsf, lcOiCil = s.lcOiCil, lcOiEje = s.lcOiEje,
        lcRadioBaseOd = s.lcRadioBaseOd, lcDiametroOd = s.lcOdDia,
        lcRadioBaseOi = s.lcRadioBaseOi, lcDiametroOi = s.lcOiDia,
        lcLaboratorio = s.lcLaboratorio, lcTipoLente = s.lcTipoLente,
        lcMaterial = s.lcMaterial, lcFechaAdaptacion = s.lcFechaAdaptacion,
        lcObservaciones = s.lcObservaciones,
    )
}

fun EvaluacionClinica.toEvaluacionUiState(): EvaluacionUiState {
    val e = this
    return EvaluacionUiState(
        isLoading = false,
        fecha = e.fecha,
        motivoConsulta = e.motivoConsulta.orEmpty(),
        sintomas = e.sintomas.orEmpty(),
        antecedentesPersonalesOculares = e.antecedentesPersonalesOculares.orEmpty(),
        antecedentesPersonalesSistemicos = e.antecedentesPersonalesSistemicos.orEmpty(),
        antecedentesFamiliaresOculares = e.antecedentesFamiliaresOculares.orEmpty(),
        antecedentesFamiliaresSistemicos = e.antecedentesFamiliaresSistemicos.orEmpty(),
        medicacion = e.medicacion.orEmpty(),
        alergias = e.alergias.orEmpty(),
        necesidadVisual = e.necesidadVisual.orEmpty(),
        avScOdLejos = e.avScOdLejos.orEmpty(), avScOiLejos = e.avScOiLejos.orEmpty(),
        avScOdCerca = e.avScOdCerca.orEmpty(), avScOiCerca = e.avScOiCerca.orEmpty(),
        avScAo = e.avScAo.orEmpty(), avScAoCerca = e.avScAoCerca.orEmpty(),
        avCcOdLejos = e.avCcOdLejos.orEmpty(), avCcOiLejos = e.avCcOiLejos.orEmpty(),
        avCcOdCerca = e.avCcOdCerca.orEmpty(), avCcOiCerca = e.avCcOiCerca.orEmpty(),
        avCcAoPx = e.avCcAoPx.orEmpty(), avCcAoCerca = e.avCcAoCerca.orEmpty(),
        phOd = e.phOd.orEmpty(), phOi = e.phOi.orEmpty(),
        kappaOd = e.kappaOd.orEmpty(), kappaOi = e.kappaOi.orEmpty(),
        hirshberg = e.hirshberg.orEmpty(),
        duccionesOd = e.duccionesOd.orEmpty(), duccionesOi = e.duccionesOi.orEmpty(),
        versionesAo = e.versionesAo.orEmpty(),
        estereopsisValor = e.estereopsisValor.orEmpty(),
        estereopsisSegundos = e.estereopsisSegundos.orEmpty(),
        lang = e.lang.orEmpty(), worth = e.worth.orEmpty(),
        ishihara = e.ishihara.orEmpty(), farnsworth = e.farnsworth.orEmpty(),
        schirmerOd = e.schirmerOd.orEmpty(), schirmerOi = e.schirmerOi.orEmpty(),
        osdiPuntuacion = e.osdiPuntuacion, osdiClasificacion = e.osdiClasificacion.orEmpty(),
        sensibilidadContraste = e.sensibilidadContraste.orEmpty(), sensibilidadFrecuencia = e.sensibilidadFrecuencia.orEmpty(),
        amsler = e.amsler.orEmpty(), campoVisual = e.campoVisual.orEmpty(), campoVisualDescripcion = e.campoVisualDescripcion.orEmpty(),
        coverTest6m = e.coverTest6m.orEmpty(), coverTest40cm = e.coverTest40cm.orEmpty(), coverTest10cm = e.coverTest10cm.orEmpty(),
        ppcOr = e.ppcOr.orEmpty(), ppcLuz = e.ppcLuz.orEmpty(), ppcFrl = e.ppcFrl.orEmpty(),
        reflejoFotomotor = e.reflejoFotomotor.orEmpty(), reflejoConsensual = e.reflejoConsensual.orEmpty(), reflejoAcomodativo = e.reflejoAcomodativo.orEmpty(),
        k1Od = e.k1Od.orEmpty(), k2Od = e.k2Od.orEmpty(), k1Oi = e.k1Oi.orEmpty(), k2Oi = e.k2Oi.orEmpty(),
        objOdEsf = e.objOdEsf.orEmpty(), objOdCil = e.objOdCil.orEmpty(), objOdEje = e.objOdEje.orEmpty(),
        objOiEsf = e.objOiEsf.orEmpty(), objOiCil = e.objOiCil.orEmpty(), objOiEje = e.objOiEje.orEmpty(),
        subjOdEsf = e.subjOdEsf.orEmpty(), subjOdCil = e.subjOdCil.orEmpty(), subjOdEje = e.subjOdEje.orEmpty(),
        subjOiEsf = e.subjOiEsf.orEmpty(), subjOiCil = e.subjOiCil.orEmpty(), subjOiEje = e.subjOiEje.orEmpty(),
        recetaOdEsf = e.recetaOdEsf.orEmpty(), recetaOdCil = e.recetaOdCil.orEmpty(), recetaOdEje = e.recetaOdEje.orEmpty(), recetaOdAv = e.recetaOdAv.orEmpty(),
        recetaOiEsf = e.recetaOiEsf.orEmpty(), recetaOiCil = e.recetaOiCil.orEmpty(), recetaOiEje = e.recetaOiEje.orEmpty(), recetaOiAv = e.recetaOiAv.orEmpty(),
        addCercaOd = e.addCercaOd.orEmpty(), addCercaOi = e.addCercaOi.orEmpty(),
        addIntermediaOd = e.addIntermediaOd.orEmpty(), addIntermediaOi = e.addIntermediaOi.orEmpty(),
        addAv = e.addAv.orEmpty(),
        dipLejos = e.dipLejos.orEmpty(), dipCerca = e.dipCerca.orEmpty(), dipIntermedio = e.dipIntermedio.orEmpty(),
        prismaOdValor = e.prismaOdValor.orEmpty(), prismaOdBase = e.prismaOdBase.orEmpty(),
        prismaOiValor = e.prismaOiValor.orEmpty(), prismaOiBase = e.prismaOiBase.orEmpty(),
        diagnostico = e.diagnostico.orEmpty(),
        diagnosticoOd = e.diagnosticoOd.orEmpty(),
        diagnosticoOi = e.diagnosticoOi.orEmpty(),
        diagnosticoOtros = e.diagnosticoOtros.orEmpty(),
        planTratamiento = e.planTratamiento.orEmpty(),
        observaciones = e.observaciones.orEmpty(),
        proximaFechaControl = e.proximaFechaControl.orEmpty(),
        proximaCita = e.proximaCita,
        citaEstado = e.citaEstado.orEmpty().ifBlank { "programada" },
        balanceOd = e.balanceOd ?: false,
        balanceOi = e.balanceOi ?: false,
        otrosPresbicia = e.otrosPresbicia ?: false,
        otrosAnisometropia = e.otrosAnisometropia ?: false,
        otrosAmbliopia = e.otrosAmbliopia ?: false,
        autoPresbicia = e.autoPresbicia ?: true,
        autoAnisometropia = e.autoAnisometropia ?: true,
        autoAmbliopia = e.autoAmbliopia ?: true,
        lcOdEsf = e.lcOdEsf.orEmpty(), lcOdCil = e.lcOdCil.orEmpty(), lcOdEje = e.lcOdEje.orEmpty(),
        lcOiEsf = e.lcOiEsf.orEmpty(), lcOiCil = e.lcOiCil.orEmpty(), lcOiEje = e.lcOiEje.orEmpty(),
        lcRadioBaseOd = e.lcRadioBaseOd.orEmpty(), lcOdDia = e.lcDiametroOd.orEmpty(),
        lcRadioBaseOi = e.lcRadioBaseOi.orEmpty(), lcOiDia = e.lcDiametroOi.orEmpty(),
        lcLaboratorio = e.lcLaboratorio.orEmpty(), lcTipoLente = e.lcTipoLente.orEmpty(),
        lcMaterial = e.lcMaterial.orEmpty(), lcFechaAdaptacion = e.lcFechaAdaptacion,
        lcObservaciones = e.lcObservaciones.orEmpty(),
        hasAdd = e.addCercaOd?.isNotEmpty() == true ||
            e.addCercaOi?.isNotEmpty() == true ||
            e.addIntermediaOd?.isNotEmpty() == true ||
            e.addIntermediaOi?.isNotEmpty() == true ||
            e.addAv?.isNotEmpty() == true,
        isAddAo = e.addCercaOd?.isNotEmpty() == true && e.addCercaOd == e.addCercaOi,
    )
}
