package com.example.optoapp.viewmodel

import com.example.optoapp.data.EvaluacionClinica
import java.util.UUID

fun EvaluacionUiState.toEvaluacionClinica(
    evaluacionId: String?,
    pacienteId: String,
    opticaId: String,
    dipParsed: DipParseResult
): EvaluacionClinica {
    val s = this
    return EvaluacionClinica(
        id = evaluacionId ?: UUID.randomUUID().toString(),
        pacienteId = pacienteId,
        fecha = s.fecha,
        opticaId = opticaId,
        motivoConsulta = s.motivoConsulta,
        sintomas = s.sintomas,
        antecedentesPersonalesOculares = s.antecedentesPersonalesOculares,
        antecedentesPersonalesSistemicos = s.antecedentesPersonalesSistemicos,
        antecedentesFamiliaresOculares = s.antecedentesFamiliaresOculares,
        antecedentesFamiliaresSistemicos = s.antecedentesFamiliaresSistemicos,
        medicacion = s.medicacion,
        alergias = s.alergias,
        necesidadVisual = s.necesidadVisual,
        avScOdLejos = s.avScOdLejos, avScOiLejos = s.avScOiLejos,
        avScOdCerca = s.avScOdCerca, avScOiCerca = s.avScOiCerca,
        avScAo = s.avScAo, avScAoCerca = s.avScAoCerca,
        avCcOdLejos = s.avCcOdLejos, avCcOiLejos = s.avCcOiLejos,
        avCcOdCerca = s.avCcOdCerca, avCcOiCerca = s.avCcOiCerca,
        avCcAoPx = s.avCcAoPx, avCcAoCerca = s.avCcAoCerca,
        phOd = s.phOd, phOi = s.phOi, kappaOd = s.kappaOd, kappaOi = s.kappaOi,
        hirshberg = s.hirshberg,
        duccionesOd = s.duccionesOd, duccionesOi = s.duccionesOi,
        versionesAo = s.versionesAo,
        estereopsisValor = s.estereopsisValor,
        estereopsisSegundos = s.estereopsisSegundos,
        lang = s.lang, worth = s.worth,
        ishihara = s.ishihara, farnsworth = s.farnsworth,
        schirmerOd = s.schirmerOd, schirmerOi = s.schirmerOi,
        osdiPuntuacion = s.osdiPuntuacion, osdiClasificacion = s.osdiClasificacion,
        sensibilidadContraste = s.sensibilidadContraste, sensibilidadFrecuencia = s.sensibilidadFrecuencia,
        amsler = s.amsler, campoVisual = s.campoVisual, campoVisualDescripcion = s.campoVisualDescripcion,
        coverTest6m = s.coverTest6m, coverTest40cm = s.coverTest40cm, coverTest10cm = s.coverTest10cm,
        ppcOr = s.ppcOr, ppcLuz = s.ppcLuz, ppcFrl = s.ppcFrl,
        reflejoFotomotor = s.reflejoFotomotor, reflejoConsensual = s.reflejoConsensual, reflejoAcomodativo = s.reflejoAcomodativo,
        k1Od = s.k1Od, k2Od = s.k2Od, k1Oi = s.k1Oi, k2Oi = s.k2Oi,
        objOdEsf = s.objOdEsf, objOdCil = s.objOdCil, objOdEje = s.objOdEje,
        objOiEsf = s.objOiEsf, objOiCil = s.objOiCil, objOiEje = s.objOiEje,
        subjOdEsf = s.subjOdEsf, subjOdCil = s.subjOdCil, subjOdEje = s.subjOdEje,
        subjOiEsf = s.subjOiEsf, subjOiCil = s.subjOiCil, subjOiEje = s.subjOiEje,
        recetaOdEsf = s.recetaOdEsf, recetaOdCil = s.recetaOdCil, recetaOdEje = s.recetaOdEje, recetaOdAv = s.recetaOdAv,
        recetaOiEsf = s.recetaOiEsf, recetaOiCil = s.recetaOiCil, recetaOiEje = s.recetaOiEje, recetaOiAv = s.recetaOiAv,
        addCercaOd = s.addCercaOd, addCercaOi = s.addCercaOi,
        addIntermediaOd = s.addIntermediaOd, addIntermediaOi = s.addIntermediaOi, addAv = s.addAv,
        dipLejos = s.dipLejos.trim(), dipCerca = s.dipCerca, dipIntermedio = s.dipIntermedio,
        dipTotalMm = dipParsed.dipTotalMm,
        dnpOdMm = dipParsed.dnpOdMm,
        dnpOiMm = dipParsed.dnpOiMm,
        prismaOdValor = s.prismaOdValor, prismaOdBase = s.prismaOdBase,
        prismaOiValor = s.prismaOiValor, prismaOiBase = s.prismaOiBase,
        diagnostico = s.diagnostico,
        diagnosticoOd = s.diagnosticoOd,
        diagnosticoOi = s.diagnosticoOi,
        diagnosticoOtros = s.diagnosticoOtros,
        planTratamiento = s.planTratamiento,
        observaciones = s.observaciones,
        proximaCita = s.proximaCita,
        citaEstado = s.citaEstado.trim().ifBlank { "programada" },
        balanceOd = s.balanceOd,
        balanceOi = s.balanceOi,
        otrosPresbicia = s.otrosPresbicia,
        otrosAnisometropia = s.otrosAnisometropia,
        otrosAmbliopia = s.otrosAmbliopia,
        autoAmbliopia = s.autoAmbliopia,
        lcOdEsf = s.lcOdEsf, lcOdCil = s.lcOdCil, lcOdEje = s.lcOdEje,
        lcOiEsf = s.lcOiEsf, lcOiCil = s.lcOiCil, lcOiEje = s.lcOiEje,
        lcRadioBaseOd = s.lcRadioBaseOd, lcDiametroOd = s.lcOdDia,
        lcRadioBaseOi = s.lcRadioBaseOi, lcDiametroOi = s.lcOiDia,
        lcLaboratorio = s.lcLaboratorio, lcTipoLente = s.lcTipoLente,
        lcMaterial = s.lcMaterial, lcFechaAdaptacion = s.lcFechaAdaptacion,
        lcObservaciones = s.lcObservaciones
    )
}

fun EvaluacionClinica.toEvaluacionUiState(): EvaluacionUiState {
    val e = this
    return EvaluacionUiState(
        isLoading = false,
        fecha = e.fecha,
        motivoConsulta = e.motivoConsulta,
        sintomas = e.sintomas,
        antecedentesPersonalesOculares = e.antecedentesPersonalesOculares,
        antecedentesPersonalesSistemicos = e.antecedentesPersonalesSistemicos,
        antecedentesFamiliaresOculares = e.antecedentesFamiliaresOculares,
        antecedentesFamiliaresSistemicos = e.antecedentesFamiliaresSistemicos,
        medicacion = e.medicacion,
        alergias = e.alergias,
        necesidadVisual = e.necesidadVisual,
        avScOdLejos = e.avScOdLejos, avScOiLejos = e.avScOiLejos,
        avScOdCerca = e.avScOdCerca, avScOiCerca = e.avScOiCerca,
        avScAo = e.avScAo, avScAoCerca = e.avScAoCerca,
        avCcOdLejos = e.avCcOdLejos, avCcOiLejos = e.avCcOiLejos,
        avCcOdCerca = e.avCcOdCerca, avCcOiCerca = e.avCcOiCerca,
        avCcAoPx = e.avCcAoPx, avCcAoCerca = e.avCcAoCerca,
        phOd = e.phOd, phOi = e.phOi,
        kappaOd = e.kappaOd, kappaOi = e.kappaOi,
        hirshberg = e.hirshberg,
        duccionesOd = e.duccionesOd, duccionesOi = e.duccionesOi,
        versionesAo = e.versionesAo,
        estereopsisValor = e.estereopsisValor,
        estereopsisSegundos = e.estereopsisSegundos,
        lang = e.lang, worth = e.worth,
        ishihara = e.ishihara, farnsworth = e.farnsworth,
        schirmerOd = e.schirmerOd, schirmerOi = e.schirmerOi,
        osdiPuntuacion = e.osdiPuntuacion, osdiClasificacion = e.osdiClasificacion,
        sensibilidadContraste = e.sensibilidadContraste, sensibilidadFrecuencia = e.sensibilidadFrecuencia,
        amsler = e.amsler, campoVisual = e.campoVisual, campoVisualDescripcion = e.campoVisualDescripcion,
        coverTest6m = e.coverTest6m, coverTest40cm = e.coverTest40cm, coverTest10cm = e.coverTest10cm,
        ppcOr = e.ppcOr, ppcLuz = e.ppcLuz, ppcFrl = e.ppcFrl,
        reflejoFotomotor = e.reflejoFotomotor, reflejoConsensual = e.reflejoConsensual, reflejoAcomodativo = e.reflejoAcomodativo,
        k1Od = e.k1Od, k2Od = e.k2Od, k1Oi = e.k1Oi, k2Oi = e.k2Oi,
        objOdEsf = e.objOdEsf, objOdCil = e.objOdCil, objOdEje = e.objOdEje,
        objOiEsf = e.objOiEsf, objOiCil = e.objOiCil, objOiEje = e.objOiEje,
        subjOdEsf = e.subjOdEsf, subjOdCil = e.subjOdCil, subjOdEje = e.subjOdEje,
        subjOiEsf = e.subjOiEsf, subjOiCil = e.subjOiCil, subjOiEje = e.subjOiEje,
        recetaOdEsf = e.recetaOdEsf, recetaOdCil = e.recetaOdCil, recetaOdEje = e.recetaOdEje, recetaOdAv = e.recetaOdAv,
        recetaOiEsf = e.recetaOiEsf, recetaOiCil = e.recetaOiCil, recetaOiEje = e.recetaOiEje, recetaOiAv = e.recetaOiAv,
        addCercaOd = e.addCercaOd, addCercaOi = e.addCercaOi,
        addIntermediaOd = e.addIntermediaOd, addIntermediaOi = e.addIntermediaOi,
        addAv = e.addAv,
        dipLejos = e.dipLejos, dipCerca = e.dipCerca, dipIntermedio = e.dipIntermedio,
        prismaOdValor = e.prismaOdValor, prismaOdBase = e.prismaOdBase,
        prismaOiValor = e.prismaOiValor, prismaOiBase = e.prismaOiBase,
        diagnostico = e.diagnostico,
        diagnosticoOd = e.diagnosticoOd,
        diagnosticoOi = e.diagnosticoOi,
        diagnosticoOtros = e.diagnosticoOtros,
        planTratamiento = e.planTratamiento,
        observaciones = e.observaciones,
        proximaCita = e.proximaCita,
        citaEstado = e.citaEstado.ifBlank { "programada" },
        balanceOd = e.balanceOd,
        balanceOi = e.balanceOi,
        otrosPresbicia = e.otrosPresbicia,
        otrosAnisometropia = e.otrosAnisometropia,
        otrosAmbliopia = e.otrosAmbliopia,
        autoPresbicia = e.autoPresbicia,
        autoAnisometropia = e.autoAnisometropia,
        autoAmbliopia = e.autoAmbliopia,
        lcOdEsf = e.lcOdEsf, lcOdCil = e.lcOdCil, lcOdEje = e.lcOdEje,
        lcOiEsf = e.lcOiEsf, lcOiCil = e.lcOiCil, lcOiEje = e.lcOiEje,
        lcRadioBaseOd = e.lcRadioBaseOd, lcOdDia = e.lcDiametroOd,
        lcRadioBaseOi = e.lcRadioBaseOi, lcOiDia = e.lcDiametroOi,
        lcLaboratorio = e.lcLaboratorio, lcTipoLente = e.lcTipoLente,
        lcMaterial = e.lcMaterial, lcFechaAdaptacion = e.lcFechaAdaptacion,
        lcObservaciones = e.lcObservaciones,
        hasAdd = e.addCercaOd.isNotEmpty() || e.addCercaOi.isNotEmpty() ||
            e.addIntermediaOd.isNotEmpty() || e.addIntermediaOi.isNotEmpty() ||
            e.addAv.isNotEmpty(),
        isAddAo = e.addCercaOd.isNotEmpty() && e.addCercaOd == e.addCercaOi
    )
}
