ALTER TABLE monturas ADD COLUMN IF NOT EXISTS ancho_mm REAL;
ALTER TABLE monturas ADD COLUMN IF NOT EXISTS puente_mm REAL;
ALTER TABLE monturas ADD COLUMN IF NOT EXISTS altura_mm REAL;
ALTER TABLE monturas ADD COLUMN IF NOT EXISTS imagen_uri TEXT;;
